import { BIOMES } from "./biome.js";

export const BIOME_GUIDE = {
  limgrave_west: {
    chapter: "Chapitre I",
    region: "Necrolimbe",
    x: 10,
    y: 16,
    recommendedLevel: [1, 8],
    danger: "Faible",
    focus: "Prise en main, premiers builds, survie simple.",
    pathRole: "Point de depart",
  },
  limgrave_east: {
    chapter: "Chapitre I",
    region: "Necrolimbe",
    x: 22,
    y: 16,
    recommendedLevel: [8, 16],
    danger: "Modere",
    focus: "Premiers duels solides, montee dex/bleed.",
    pathRole: "Route agressive",
  },
  limgrave_north: {
    chapter: "Chapitre I",
    region: "Necrolimbe",
    x: 18,
    y: 6,
    recommendedLevel: [12, 20],
    danger: "Modere",
    focus: "Verrou de progression vers le premier grand chateau.",
    pathRole: "Route principale",
  },
  limgrave_lake: {
    chapter: "Chapitre I",
    region: "Necrolimbe",
    x: 10,
    y: 31,
    recommendedLevel: [10, 18],
    danger: "Modere",
    focus: "Option feu/intelligence et dragon precoce.",
    pathRole: "Detour optionnel",
  },
  weeping_peninsula: {
    chapter: "Chapitre II",
    region: "Sud",
    x: 22,
    y: 31,
    recommendedLevel: [16, 26],
    danger: "Modere",
    focus: "Transition vers le tier 3, debut des builds givre.",
    pathRole: "Branche sud",
  },
  morne_castle: {
    chapter: "Chapitre II",
    region: "Sud",
    x: 22,
    y: 45,
    recommendedLevel: [22, 32],
    danger: "Eleve",
    focus: "Test force/bleed, gain d'armes lourdes.",
    pathRole: "Cul-de-sac rentable",
  },
  enter_stormwind_castle: {
    chapter: "Chapitre II",
    region: "Voile Orage",
    x: 31,
    y: 6,
    recommendedLevel: [18, 28],
    danger: "Eleve",
    focus: "Porte de Stormveil, combat plus technique.",
    pathRole: "Route principale",
  },
  stormwind_castle: {
    chapter: "Chapitre II",
    region: "Voile Orage",
    x: 42,
    y: 6,
    recommendedLevel: [26, 36],
    danger: "Eleve",
    focus: "Premier gros check d'endurance et d'armure.",
    pathRole: "Boss gate majeur",
  },
  caelid_west: {
    chapter: "Chapitre II",
    region: "Caelid",
    x: 35,
    y: 24,
    recommendedLevel: [22, 34],
    danger: "Eleve",
    focus: "Zone risk/reward, statuts et armures denses.",
    pathRole: "Detour risqué",
  },
  liurnia_south: {
    chapter: "Chapitre III",
    region: "Liurnia",
    x: 54,
    y: 11,
    recommendedLevel: [32, 42],
    danger: "Eleve",
    focus: "Ouverture caster et multi-builds de midgame.",
    pathRole: "Route principale",
  },
  liurnia_west: {
    chapter: "Chapitre III",
    region: "Liurnia",
    x: 63,
    y: 6,
    recommendedLevel: [38, 48],
    danger: "Eleve",
    focus: "Route carienne, tank/mage hybride.",
    pathRole: "Branche ouest",
  },
  liurnia_east: {
    chapter: "Chapitre III",
    region: "Liurnia",
    x: 63,
    y: 17,
    recommendedLevel: [38, 48],
    danger: "Eleve",
    focus: "Route marais, vigueur et penetration.",
    pathRole: "Branche est",
  },
  liurnia_marsh: {
    chapter: "Chapitre III",
    region: "Liurnia",
    x: 54,
    y: 24,
    recommendedLevel: [42, 52],
    danger: "Tres eleve",
    focus: "Dragon optionnel tres rentable pour les mages.",
    pathRole: "Boss optionnel",
  },
  raya_lucaria_academy: {
    chapter: "Chapitre III",
    region: "Liurnia",
    x: 73,
    y: 11,
    recommendedLevel: [45, 58],
    danger: "Tres eleve",
    focus: "Pivot midgame, sets academie et crystal.",
    pathRole: "Route principale",
  },
  caria_mansion: {
    chapter: "Chapitre IV",
    region: "Nord des lacs",
    x: 73,
    y: 3,
    recommendedLevel: [48, 60],
    danger: "Tres eleve",
    focus: "Monte en puissance controle/givre.",
    pathRole: "Branche ouest",
  },
  caelid_south: {
    chapter: "Chapitre IV",
    region: "Caelid",
    x: 47,
    y: 28,
    recommendedLevel: [40, 54],
    danger: "Tres eleve",
    focus: "Endurance sous pression et packs brutaux.",
    pathRole: "Route alternative",
  },
  caelid_dragonbarrow: {
    chapter: "Chapitre IV",
    region: "Caelid",
    x: 47,
    y: 40,
    recommendedLevel: [50, 64],
    danger: "Tres eleve",
    focus: "Dragon optionnel et loot corruption.",
    pathRole: "Boss optionnel",
  },
  siofra_river: {
    chapter: "Chapitre IV",
    region: "Souterrain",
    x: 82,
    y: 21,
    recommendedLevel: [52, 64],
    danger: "Tres eleve",
    focus: "Route controle/stun et sustain.",
    pathRole: "Branche souterraine",
  },
  redmane_castle: {
    chapter: "Chapitre IV",
    region: "Caelid",
    x: 58,
    y: 34,
    recommendedLevel: [55, 68],
    danger: "Tres eleve",
    focus: "Grand mur de puissance physique.",
    pathRole: "Route principale bis",
  },
  nokron: {
    chapter: "Chapitre V",
    region: "Souterrain",
    x: 90,
    y: 28,
    recommendedLevel: [62, 74],
    danger: "Tres eleve",
    focus: "Pivot late midgame, builds polymorphes.",
    pathRole: "Noeud de bascule",
  },
  ainsel_river: {
    chapter: "Chapitre V",
    region: "Souterrain",
    x: 90,
    y: 43,
    recommendedLevel: [68, 80],
    danger: "Tres eleve",
    focus: "Nouvelle route astrale dex/int a haut tempo.",
    pathRole: "Nouvelle branche v2",
  },
  deeproot_depths: {
    chapter: "Chapitre V",
    region: "Souterrain",
    x: 79,
    y: 45,
    recommendedLevel: [70, 82],
    danger: "Tres eleve",
    focus: "Tank/sustain et armures vivantes.",
    pathRole: "Nouvelle branche v2",
  },
  rotlake: {
    chapter: "Chapitre VI",
    region: "Souterrain",
    x: 90,
    y: 58,
    recommendedLevel: [78, 92],
    danger: "Extrem",
    focus: "Endgame optionnel axe statuts et survie active.",
    pathRole: "Detour v2 endgame",
  },
  altus_plateau: {
    chapter: "Chapitre VI",
    region: "Altus",
    x: 84,
    y: 8,
    recommendedLevel: [78, 100],
    danger: "Extrem",
    focus: "Frontiere du late game terrestre.",
    pathRole: "Route principale",
    hazards: ["folie"],
  },
  mount_gelmir: {
    chapter: "Chapitre VII",
    region: "Gelmir",
    x: 95,
    y: 16,
    recommendedLevel: [94, 118],
    danger: "Extrem",
    focus: "Volcan, venins et predateurs draconiques en crescendo.",
    pathRole: "Route principale",
    hazards: ["poison", "putrefaction"],
  },
  mountaintops: {
    chapter: "Chapitre VIII",
    region: "Cimes",
    x: 95,
    y: 4,
    recommendedLevel: [110, 134],
    danger: "Extrem",
    focus: "Glace, posture et geants. Un mur de lecture et de tempo.",
    pathRole: "Route principale",
    hazards: ["gel", "folie"],
  },
  crumbling_farum_azula: {
    chapter: "Chapitre IX",
    region: "Azula",
    x: 99,
    y: 28,
    recommendedLevel: [126, 150],
    danger: "Abyssal",
    focus: "Ruines suspendues, tempetes sacrileges et reliques noires.",
    pathRole: "Fin de route terrestre",
    hazards: ["folie", "putrefaction"],
  },
  // --- Contenu en chantier -----------------------------------------
  // Ces sept biomes existaient dans biome.js sans entree ici. Sans
  // coordonnees, ils basculaient sur la disposition automatique, qui vit dans
  // un tout autre repere (depth * 240 contre x * 18) : ils atterrissaient a
  // des centaines de pixels des autres et faisaient exploser le cadrage de la
  // carte. Ils sont marques wip pour etre affiches en retrait.
  leyndell_royal: {
    chapter: "Chapitre VIII",
    region: "Leyndell",
    x: 88,
    y: 11,
    recommendedLevel: [110, 130],
    danger: "Extreme",
    focus: "Capitale doree, gardes royaux et longues avenues.",
    pathRole: "Route royale",
    wip: true,
  },
  forbidden_land: {
    chapter: "Chapitre VIII",
    region: "Cimes",
    x: 92,
    y: 7,
    recommendedLevel: [112, 134],
    danger: "Extreme",
    focus: "Col battu par les vents avant les sommets.",
    pathRole: "Passage vers les Cimes",
    wip: true,
  },
  consecrated_snowfield: {
    chapter: "Chapitre IX",
    region: "Cimes",
    x: 92,
    y: 48,
    recommendedLevel: [120, 140],
    danger: "Extreme",
    focus: "Plaine blanche ou l'on ne voit pas a dix pas.",
    pathRole: "Route cachee",
    wip: true,
  },
  mohgwyn_palace: {
    chapter: "Chapitre IX",
    region: "Souterrain",
    x: 96,
    y: 52,
    recommendedLevel: [124, 144],
    danger: "Abyssal",
    focus: "Lac de sang sous une lune rouge.",
    pathRole: "Detour sanglant",
    wip: true,
  },
  miquella_haligtree: {
    chapter: "Chapitre IX",
    region: "Arbre Sacre",
    x: 100,
    y: 44,
    recommendedLevel: [130, 148],
    danger: "Abyssal",
    focus: "Ramures suspendues et gardiens putrides.",
    pathRole: "Voie alternative vers Azula",
    wip: true,
  },
  Leyndell_ash: {
    chapter: "Chapitre X",
    region: "Leyndell",
    x: 104,
    y: 22,
    recommendedLevel: [136, 150],
    danger: "Abyssal",
    focus: "La capitale ensevelie sous la cendre.",
    pathRole: "Avant-derniere etape",
    wip: true,
  },
  erdTree: {
    chapter: "Chapitre X",
    region: "Arbre-Monde",
    x: 108,
    y: 28,
    recommendedLevel: [140, 150],
    danger: "Abyssal",
    focus: "Le terme de la route.",
    pathRole: "Terminus",
    wip: true,
  },
};

export const BIOME_ORDER = Object.keys(BIOME_GUIDE);

export function getBiomeGraphDepth(biomeId, seen = new Map()) {
  if (seen.has(biomeId)) return seen.get(biomeId);
  const biome = BIOMES[biomeId];
  if (!biome) return 0;

  let parents = 0;
  Object.entries(BIOMES).forEach(([candidateId, candidate]) => {
    if ((candidate.unlocks || []).includes(biomeId)) {
      parents = Math.max(parents, getBiomeGraphDepth(candidateId, seen) + 1);
    }
  });

  seen.set(biomeId, parents);
  return parents;
}

export function getBiomePowerBand(biomeId) {
  const guide = BIOME_GUIDE[biomeId];
  if (!guide) return "Inconnu";
  return `Niv. ${guide.recommendedLevel[0]}-${guide.recommendedLevel[1]}`;
}

export function getBiomeDangerClass(biomeId) {
  const danger = BIOME_GUIDE[biomeId]?.danger || "";
  return danger
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, "-");
}
