import { BIOMES } from "./biome.js";

export const BIOME_GUIDE = {
  limgrave_west: {
    chapter: "Chapitre I",
    region: "Necrolimbe",
    x: 10,
    y: 16,
    recommendedLevel: [6, 12],
    danger: "Faible",
    focus: "Prise en main, premiers builds, survie simple.",
    pathRole: "Point de depart",
  },
  limgrave_east: {
    chapter: "Chapitre I",
    region: "Necrolimbe",
    x: 22,
    y: 16,
    recommendedLevel: [15, 24],
    danger: "Modere",
    focus: "Premiers duels solides, montee dex/bleed.",
    pathRole: "Route agressive",
  },
  limgrave_north: {
    chapter: "Chapitre I",
    region: "Necrolimbe",
    x: 18,
    y: 6,
    recommendedLevel: [22, 29],
    danger: "Modere",
    focus: "Verrou de progression vers le premier grand chateau.",
    pathRole: "Route principale",
  },
  limgrave_lake: {
    chapter: "Chapitre I",
    region: "Necrolimbe",
    x: 10,
    y: 31,
    recommendedLevel: [29, 36],
    danger: "Modere",
    focus: "Option feu/intelligence et dragon precoce.",
    pathRole: "Detour optionnel",
  },
  weeping_peninsula: {
    chapter: "Chapitre II",
    region: "Sud",
    x: 22,
    y: 31,
    recommendedLevel: [27, 35],
    danger: "Modere",
    focus: "Transition vers le tier 3, debut des builds givre.",
    pathRole: "Branche sud",
  },
  morne_castle: {
    chapter: "Chapitre II",
    region: "Sud",
    x: 22,
    y: 45,
    recommendedLevel: [39, 57],
    danger: "Eleve",
    focus: "Test force/bleed, gain d'armes lourdes.",
    pathRole: "Cul-de-sac rentable",
  },
  enter_stormwind_castle: {
    chapter: "Chapitre II",
    region: "Voile Orage",
    x: 31,
    y: 6,
    recommendedLevel: [33, 46],
    danger: "Eleve",
    focus: "Porte de Stormveil, combat plus technique.",
    pathRole: "Route principale",
  },
  stormwind_castle: {
    chapter: "Chapitre II",
    region: "Voile Orage",
    x: 42,
    y: 6,
    recommendedLevel: [26, 36],
    danger: "Eleve",
    focus: "Premier gros check d'endurance et d'armure.",
    pathRole: "Boss gate majeur",
  },
  caelid_west: {
    chapter: "Chapitre II",
    region: "Caelid",
    x: 35,
    y: 24,
    recommendedLevel: [49, 68],
    danger: "Eleve",
    focus: "Zone risk/reward, statuts et armures denses.",
    pathRole: "Detour risqué",
  },
  liurnia_south: {
    chapter: "Chapitre III",
    region: "Liurnia",
    x: 54,
    y: 11,
    recommendedLevel: [45, 62],
    danger: "Eleve",
    focus: "Ouverture caster et multi-builds de midgame.",
    pathRole: "Route principale",
  },
  liurnia_west: {
    chapter: "Chapitre III",
    region: "Liurnia",
    x: 63,
    y: 6,
    recommendedLevel: [48, 65],
    danger: "Eleve",
    focus: "Route carienne, tank/mage hybride.",
    pathRole: "Branche ouest",
  },
  liurnia_east: {
    chapter: "Chapitre III",
    region: "Liurnia",
    x: 63,
    y: 17,
    recommendedLevel: [50, 67],
    danger: "Eleve",
    focus: "Route marais, vigueur et penetration.",
    pathRole: "Branche est",
  },
  liurnia_marsh: {
    chapter: "Chapitre III",
    region: "Liurnia",
    x: 54,
    y: 24,
    recommendedLevel: [50, 70],
    danger: "Tres eleve",
    focus: "Dragon optionnel tres rentable pour les mages.",
    pathRole: "Boss optionnel",
  },
  raya_lucaria_academy: {
    chapter: "Chapitre III",
    region: "Liurnia",
    x: 73,
    y: 11,
    recommendedLevel: [52, 70],
    danger: "Tres eleve",
    focus: "Pivot midgame, sets academie et crystal.",
    pathRole: "Route principale",
  },
  caria_mansion: {
    chapter: "Chapitre IV",
    region: "Nord des lacs",
    x: 73,
    y: 3,
    recommendedLevel: [90, 110],
    danger: "Tres eleve",
    focus: "Monte en puissance controle/givre.",
    pathRole: "Branche ouest",
  },
  caelid_south: {
    chapter: "Chapitre IV",
    region: "Caelid",
    x: 47,
    y: 28,
    recommendedLevel: [64, 84],
    danger: "Tres eleve",
    focus: "Endurance sous pression et packs brutaux.",
    pathRole: "Route alternative",
  },
  caelid_dragonbarrow: {
    chapter: "Chapitre IV",
    region: "Caelid",
    x: 47,
    y: 40,
    recommendedLevel: [120, 155],
    danger: "Tres eleve",
    focus: "Dragon optionnel et loot corruption.",
    pathRole: "Boss optionnel",
  },
  siofra_river: {
    chapter: "Chapitre IV",
    region: "Souterrain",
    x: 82,
    y: 21,
    recommendedLevel: [79, 103],
    danger: "Tres eleve",
    focus: "Route controle/stun et sustain.",
    pathRole: "Branche souterraine",
  },
  redmane_castle: {
    chapter: "Chapitre IV",
    region: "Caelid",
    x: 58,
    y: 34,
    recommendedLevel: [117, 150],
    danger: "Tres eleve",
    focus: "Grand mur de puissance physique.",
    pathRole: "Route principale bis",
  },
  nokron: {
    chapter: "Chapitre V",
    region: "Souterrain",
    x: 90,
    y: 28,
    recommendedLevel: [116, 150],
    danger: "Tres eleve",
    focus: "Pivot late midgame, builds polymorphes.",
    pathRole: "Noeud de bascule",
  },
  ainsel_river: {
    chapter: "Chapitre V",
    region: "Souterrain",
    x: 90,
    y: 43,
    recommendedLevel: [155, 194],
    danger: "Tres eleve",
    focus: "Nouvelle route astrale dex/int a haut tempo.",
    pathRole: "Nouvelle branche v2",
  },
  deeproot_depths: {
    chapter: "Chapitre V",
    region: "Souterrain",
    x: 79,
    y: 45,
    recommendedLevel: [160, 202],
    danger: "Tres eleve",
    focus: "Tank/sustain et armures vivantes.",
    pathRole: "Nouvelle branche v2",
  },
  rotlake: {
    chapter: "Chapitre VI",
    region: "Souterrain",
    x: 90,
    y: 58,
    recommendedLevel: [125, 147],
    danger: "Extrem",
    focus: "Endgame optionnel axe statuts et survie active.",
    pathRole: "Detour v2 endgame",
  },
  altus_plateau: {
    chapter: "Chapitre VI",
    region: "Altus",
    x: 84,
    y: 8,
    recommendedLevel: [160, 200],
    danger: "Extrem",
    focus: "Frontiere du late game terrestre.",
    pathRole: "Route principale",
    hazards: ["folie"],
  },
  mount_gelmir: {
    chapter: "Chapitre VII",
    region: "Gelmir",
    x: 95,
    y: 16,
    recommendedLevel: [150, 189],
    danger: "Extrem",
    focus: "Volcan, venins et predateurs draconiques en crescendo.",
    pathRole: "Route principale",
    hazards: ["poison", "putrefaction"],
  },
  mountaintops: {
    chapter: "Chapitre VIII",
    region: "Cimes",
    x: 95,
    y: 4,
    recommendedLevel: [176, 214],
    danger: "Extrem",
    focus: "Glace, posture et geants. Un mur de lecture et de tempo.",
    pathRole: "Route principale",
    hazards: ["gel", "folie"],
  },
  crumbling_farum_azula: {
    chapter: "Chapitre IX",
    region: "Azula",
    x: 99,
    y: 28,
    recommendedLevel: [201, 220],
    danger: "Abyssal",
    focus: "Ruines suspendues, tempetes sacrileges et reliques noires.",
    pathRole: "Fin de route terrestre",
    hazards: ["folie", "putrefaction"],
  },
  // --- Fin de parcours ---------------------------------------------
  // Ces biomes existaient dans biome.js sans entree ici. Sans coordonnees, ils
  // basculaient sur la disposition automatique, qui vit dans un tout autre
  // repere (depth * 240 contre x * 18) : ils atterrissaient a des centaines de
  // pixels des autres et faisaient exploser le cadrage de la carte.
  //
  // Tous ont desormais un contenu jouable. Les deux souches vides qui
  // restaient dans biome.js (Leyndell_ash, erdTree) ont ete remplacees par les
  // vrais biomes leyndell_ash et erdtree_throne du chapitre X.
  leyndell_royal: {
    chapter: "Chapitre VIII",
    region: "Leyndell",
    x: 88,
    y: 11,
    recommendedLevel: [176, 208],
    danger: "Extreme",
    focus: "Capitale doree, gardes royaux et longues avenues.",
    pathRole: "Route royale",
  },
  forbidden_land: {
    chapter: "Chapitre VIII",
    region: "Cimes",
    x: 92,
    y: 7,
    recommendedLevel: [179, 214],
    danger: "Extreme",
    focus: "Col battu par les vents avant les sommets.",
    pathRole: "Passage vers les Cimes",
  },
  consecrated_snowfield: {
    chapter: "Chapitre IX",
    region: "Cimes",
    x: 92,
    y: 48,
    recommendedLevel: [192, 220],
    danger: "Extreme",
    focus: "Plaine blanche ou l'on ne voit pas a dix pas.",
    pathRole: "Route cachee",
  },
  mohgwyn_palace: {
    chapter: "Chapitre IX",
    region: "Souterrain",
    x: 96,
    y: 52,
    recommendedLevel: [198, 220],
    danger: "Abyssal",
    focus: "Lac de sang sous une lune rouge.",
    pathRole: "Detour sanglant",
  },
  miquella_haligtree: {
    chapter: "Chapitre IX",
    region: "Arbre Sacre",
    x: 100,
    y: 44,
    recommendedLevel: [208, 220],
    danger: "Abyssal",
    focus: "Ramures suspendues et gardiens putrides.",
    pathRole: "Voie alternative vers Azula",
  },
  /* --- Version complete : chapitres VI a X et zones annexes ------- */

  dominula_village: {
    chapter: "Chapitre VI",
    region: "Altus",
    x: 66,
    y: 30,
    recommendedLevel: [147, 184],
    danger: "Eleve",
    focus: "Un village en fete. Les tambours accelerent et ne s'arretent jamais.",
    pathRole: "Detour d'Altus",
    hazards: ["folie"],
  },
  shaded_castle: {
    chapter: "Chapitre VI",
    region: "Altus",
    x: 70,
    y: 34,
    recommendedLevel: [138, 172],
    danger: "Eleve",
    focus: "Un chateau noye dans une brume qui ronge les poumons.",
    pathRole: "Route vers Gelmir",
    hazards: ["poison"],
  },
  volcano_manor: {
    chapter: "Chapitre VII",
    region: "Gelmir",
    x: 78,
    y: 26,
    recommendedLevel: [166, 192],
    danger: "Tres eleve",
    focus: "On y signe des contrats. On y paie bien, on n'y soigne personne.",
    pathRole: "Coeur du Mont Gelmir",
    hazards: ["folie"],
  },
  rykard_lair: {
    chapter: "Chapitre VII",
    region: "Gelmir",
    x: 82,
    y: 22,
    recommendedLevel: [173, 198],
    danger: "Tres eleve",
    focus: "Une fosse de magma et ce qui reste d'un dieu dedans.",
    pathRole: "Fin du Mont Gelmir",
    hazards: ["folie"],
  },
  divine_tower: {
    chapter: "Chapitre VIII",
    region: "Leyndell",
    x: 90,
    y: 15,
    recommendedLevel: [185, 211],
    danger: "Extreme",
    focus: "La Tour coupe le lien a la Grace. Aucun soin ne fonctionne dedans.",
    pathRole: "Detour de Leyndell",
    hazards: ["folie"],
  },
  castle_sol: {
    chapter: "Chapitre VIII",
    region: "Cimes",
    x: 94,
    y: 11,
    recommendedLevel: [192, 217],
    danger: "Extreme",
    focus: "Une nuit qui ne finit pas. On ne voit pas venir les coups.",
    pathRole: "Route du nord",
    hazards: ["gel"],
  },
  giants_catacombs: {
    chapter: "Chapitre VIII",
    region: "Cimes",
    x: 98,
    y: 8,
    recommendedLevel: [198, 220],
    danger: "Extreme",
    focus: "Des braises qui couvent depuis la guerre des Geants.",
    pathRole: "Avant les Cimes",
    hazards: ["gel", "folie"],
  },
  elphael: {
    chapter: "Chapitre IX",
    region: "Arbre Sacre",
    x: 104,
    y: 44,
    recommendedLevel: [217, 220],
    danger: "Abyssal",
    focus: "Les spores tombent en continu. Elle vous attend au bout.",
    pathRole: "Coeur de l'Arbre Sacre",
    hazards: ["putrefaction"],
  },
  farum_azula_deep: {
    chapter: "Chapitre IX",
    region: "Farum Azula",
    x: 110,
    y: 36,
    recommendedLevel: [214, 220],
    danger: "Abyssal",
    focus: "Sous les ruines, une tempete qui dure depuis avant l'Arbre.",
    pathRole: "Vers le chapitre X",
    hazards: ["folie"],
  },
  leyndell_ash: {
    chapter: "Chapitre X",
    region: "Leyndell",
    x: 116,
    y: 30,
    recommendedLevel: [214, 220],
    danger: "Abyssal",
    focus: "La capitale ensevelie sous la cendre. Elle ronge les armures.",
    pathRole: "Avant-derniere etape",
    hazards: ["putrefaction", "folie"],
  },
  erdtree_throne: {
    chapter: "Chapitre X",
    region: "Arbre-Monde",
    x: 122,
    y: 24,
    recommendedLevel: [214, 220],
    danger: "Abyssal",
    focus: "Le terme de la route. On n'en repart pas en arriere.",
    pathRole: "Terminus",
    hazards: ["folie"],
  },
  bestial_sanctum: {
    chapter: "Annexe",
    region: "Tertre Draconique",
    x: 62,
    y: 52,
    recommendedLevel: [172, 217],
    danger: "Eleve",
    focus: "Gurranq echange des racines de mort contre du butin. Aucune elite ici.",
    pathRole: "Zone de recolte",
    hazards: [],
  },
  jarburg: {
    chapter: "Annexe",
    region: "Liurnia",
    x: 86,
    y: 56,
    recommendedLevel: [40, 53],
    danger: "Faible",
    focus: "Des jarres creuses et pleines de runes. Elles se brisent vite.",
    pathRole: "Zone de runes",
    hazards: [],
  },
  evergaol_champions: {
    chapter: "Annexe",
    region: "Enclos",
    x: 114,
    y: 50,
    recommendedLevel: [214, 220],
    danger: "Abyssal",
    focus: "Quatre champions a la suite, sans repos et sans soin.",
    pathRole: "Defi de fin de partie",
    hazards: ["folie"],
  },
};

export const BIOME_ORDER = Object.keys(BIOME_GUIDE);

export function getBiomeGraphDepth(biomeId, seen = new Map()) {
  if (seen.has(biomeId)) return seen.get(biomeId);
  const biome = BIOMES[biomeId];
  if (!biome) return 0;

  let parents = 0;
  Object.entries(BIOMES).forEach(([candidateId, candidate]) => {
    if ((candidate.unlocks || []).includes(biomeId)) {
      parents = Math.max(parents, getBiomeGraphDepth(candidateId, seen) + 1);
    }
  });

  seen.set(biomeId, parents);
  return parents;
}

export function getBiomePowerBand(biomeId) {
  const guide = BIOME_GUIDE[biomeId];
  if (!guide) return "Inconnu";
  return `Niv. ${guide.recommendedLevel[0]}-${guide.recommendedLevel[1]}`;
}

export function getBiomeDangerClass(biomeId) {
  const danger = BIOME_GUIDE[biomeId]?.danger || "";
  return danger
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, "-");
}
